### ISSUE TITLE
incoming 9.2

### ISSUE THREAD

**Issue by orthagh** [joeFischetti/glpi_plugin_tasklist#1]
Hello @joeFischetti 

I just received your submission for that plugin.
It's a very cool idea but i'm confused with it.
In fact, we have a similar feature incoming in the 9.2 release of GLPI (due date: 25 this sept), see https://github.com/glpi-project/glpi/pull/1815

So for old releases, i can accept your plugin, but for the next major release, it will be redundant.

Your thoughts ?

**Comment by joeFischetti** [comment]
I had seen a thread about the feature eventually being built in but was
unaware that it was in this release. At any rate, I think it makes sense to
include it for older releases. We'll be using it until we upgrade, which
may be a while.

On Sep 14, 2017 3:19 AM, "Alexandre Delaunay" <notifications@github.com>
wrote:

Hello @joeFischetti <https://github.com/joefischetti>

I just received your submission for that plugin.
It's a very cool idea but i'm confused with it.
In fact with a similar feature incoming in the 9.2 release of GLPI (due
date: 25 this sept), see glpi-project/glpi#1815
<https://github.com/glpi-project/glpi/pull/1815>

So for old releases, i can accept your plugin, but for the next major
release, it will be redundant.

Your thoughts ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/joeFischetti/glpi_plugin_tasklist/issues/1>, or mute
the thread

**Comment by orthagh** [comment]
fine :)

It should be available right now in the [catalog](plugins.glpi-project.org)

**Comment by joeFischetti** [comment]
I added a comment to the existing issue that you originally linked. Can it be re-opened?

If the way it works in my comment is working as intended, my plugin still adds functionality even to 9.2.
